// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "db", input: never, result: Journey } | 
        { key: "greet", input: string, result: string } | 
        { key: "kvb", input: never, result: Journey } | 
        { key: "version", input: never, result: string },
    mutations: never,
    subscriptions: never
};

export type Journey = { from: string; to: string; departure: string; arrival: string; planned_depature: string; planned_arrival: string; line: string }
